//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingridient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingridient()
        {
            this.SpecifikaciaIngridients = new HashSet<SpecifikaciaIngridient>();
        }
    
        public string Id { get; set; }
        public string Articul { get; set; }
        public string Name { get; set; }
        public string EdinicyIzmerenia { get; set; }
        public string Kolichestvo { get; set; }
        public string Type { get; set; }
        public string Stoimost { get; set; }
        public string Gost { get; set; }
        public string Fasovka { get; set; }
        public string Charakteristika { get; set; }
        public string PostavshikName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecifikaciaIngridient> SpecifikaciaIngridients { get; set; }
        public virtual Postavshik Postavshik { get; set; }
    }
}
