//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TortyEntities : DbContext
    {
        public TortyEntities()
            : base("name=TortyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingridient> Ingridients { get; set; }
        public virtual DbSet<Izdelie> Izdelies { get; set; }
        public virtual DbSet<Oborudovanie> Oborudovanies { get; set; }
        public virtual DbSet<Postavshik> Postavshiks { get; set; }
        public virtual DbSet<SpecifikaciaIngridient> SpecifikaciaIngridients { get; set; }
        public virtual DbSet<SpecifikaciaOperacii> SpecifikaciaOperaciis { get; set; }
        public virtual DbSet<SpecifikaciaPolufabrikat> SpecifikaciaPolufabrikats { get; set; }
        public virtual DbSet<SpecifikaciaTort> SpecifikaciaTorts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type_oborudovania> Type_oborudovania { get; set; }
        public virtual DbSet<UkrasheniaTort> UkrasheniaTorts { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Zakazy> Zakazies { get; set; }
    }
}
