//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oborudovanie
    {
        public int Markirovka { get; set; }
        public string Type_oborudovania { get; set; }
        public string Charakteristika { get; set; }
    
        public virtual Type_oborudovania Type_oborudovania1 { get; set; }
    }
}
