//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecifikaciaOperacii
    {
        public string Izdelie { get; set; }
        public string Operacia { get; set; }
        public int Nomer { get; set; }
        public string TypeOborudovania { get; set; }
        public Nullable<System.TimeSpan> VremyaOperacii { get; set; }
    
        public virtual Izdelie Izdelie1 { get; set; }
        public virtual Type_oborudovania Type_oborudovania { get; set; }
    }
}
