//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Collections.Generic;
    
    public partial class UkrasheniaTort
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UkrasheniaTort()
        {
            this.SpecifikaciaTorts = new HashSet<SpecifikaciaTort>();
        }
    
        public string Articul { get; set; }
        public string Name { get; set; }
        public string EdinicyIzmerenia { get; set; }
        public Nullable<double> Kolichestvo { get; set; }
        public string Type { get; set; }
        public string Stoimost { get; set; }
        public string Ves { get; set; }
        public string PostavshikName { get; set; }
    
        public virtual Postavshik Postavshik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecifikaciaTort> SpecifikaciaTorts { get; set; }
    }
}
