//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tort
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazy
    {
        public int Nomer { get; set; }
        public System.DateTime Data { get; set; }
        public string NaimenovanieZakaz { get; set; }
        public string Izdelie { get; set; }
        public string Zakazchik { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> Stoimost { get; set; }
        public Nullable<System.DateTime> DataZavershenia { get; set; }
    
        public virtual Izdelie Izdelie1 { get; set; }
    }
}
